# Generated by Django 6.0.2 on 2026-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothDetails',
            fields=[
                ('cloth_details_id', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cloth_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('cloth_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('item_type', models.TextField(blank=True, max_length=6, null=True)),
                ('cloth_description', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'clothes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('colour', models.TextField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('complement', models.TextField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'colours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drawers',
            fields=[
                ('drawer_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('drawer_type', models.TextField(blank=True, null=True)),
                ('drawer_description', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'drawers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hexcodes',
            fields=[
                ('hexcode', models.TextField(blank=True, max_length=7, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hexcodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('layer_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('layer_description', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'layers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('palette_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('palette_description', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'palette',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaletteList',
            fields=[
                ('palette_list_id', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'palette_list',
                'managed': False,
            },
        ),
    ]
